### ISSUE TITLE
audio_functions.py is empty

### ISSUE THREAD

**Issue by giuliastro** [JorisdeJong123/LangChain-Unchained#1]
Hi,
the file audio_functions.py inside the repo is empty.
The script doesn't run because it can't find functions that should be inside this file.

**Comment by mishrankit9** [comment]
Hi Joris,
The audio_functions.py file is empty. Can you please update the project with the required file.

**Comment by JorisdeJong123** [comment]
Thanks for the heads up.

Fixed.
